### PR TITLE
feat(home-manager): init swaylock module

### PR DESCRIPTION
**Pull request by Anomalocaridid**
Adds support for swaylock.

In case it matters, this theme is from a third-party repo rather than one owned by the Catppuccin GitHub organization.

### CODE REVIEW

**Comment by getchoo** [comment]
please see my [comment](https://github.com/Stonks3141/ctp-nix/pull/55#issuecomment-1792655089) from https://github.com/Stonks3141/ctp-nix/pull/55

~~this one was a bit harder since i was actually thinking of picking up swaylock soon too 😞~~

**Comment by Anomalocaridid** [comment]
Closed because it has come to my attention that unofficial ports are not allowed.

**Comment by Anomalocaridid** [comment]
The swaylock theme is now official: https://github.com/catppuccin/swaylock.

I have updated my PR branch accordingly. Could this PR please be re-opened?

**Comment by Anomalocaridid** [comment]
@getchoo Could this PR please be reopened? The swaylock theme is now official and I have updated my PR branch accordingly.

Although I just noticed this PR does not show the new changes, probably because they were made after it was closed. However, going directly to my branch at https://github.com/Anomalocaridid/ctp-nix/tree/swaylock does.

I apologize if I am overstepping any boundaries by pinging you. I am not sure how visible my last comment was given that this PR was already closed and you were the only other person to interact with this PR.

**Comment by getchoo** [comment]
@Anomalocaridid sorry for not seeing this!

for some reason i can't reopen this pull request even though the branch has been restored; you'll need to make a new one if you're still up for it

**Comment by getchoo** [comment]
nevermind, after commenting i can now?

**Comment by Anomalocaridid** [comment]
That's alright. Thanks anyways.

**Pull request closed without merging**
