### PR TITLE
fix(gtk): capitalize "Light" and "Dark"

### PR DESCRIPTION
**Pull request by vgskye**
yeeeeeeah

### CODE REVIEW

**Review by getchoo — APPROVED** [review]

**Comment by getchoo** [comment]
oops, forgot to revert this

it's all good to merge, you just need to make the commit message follow the [contributing guidelines](https://github.com/Stonks3141/ctp-nix/blob/main/CONTRIBUTING.md#commit-messages)

**Comment by vgskye** [comment]
oh I didn't see that gimme a sec

**Comment by getchoo** [comment]
thanks!

**Comment by getchoo** [comment]
...and i should've squashed that /shrug

**Pull request merged**
