### PR TITLE
remove unnecessary IFD + add auto updates & testing

### LINKED ISSUE #15: Testing
I'd like to test the output of this flake with various configurations, we can probably use some kind of [expectation testing](https://matklad.github.io/2021/05/31/how-to-test.html#Expect-Tests).

I'll work on this.

### PR DESCRIPTION
**Pull request by getchoo**
by moving all upstream repos to ~~our flake inputs~~ sources generated by nvfetcher, we no longer need to have [IFD](https://nixos.wiki/wiki/Import_From_Derivation) in most of our modules - making evaluation faster for all configurations. the only remaining instances of IFD are in `lib.ctp.toYAML` and the themes for kitty, which is due to it's use upstream in home-manager. these seem unavoidable for now, but the benefits in other modules are still great. this also gives us the ability to easily update our upstream sources and access them inside of modules.

workflows have been added to assist with this, mainly `update-lock` which updates both our flake inputs and nvfetcher sources. to ensure nothing breaks from these updates, i have also created a test vm that can also be run when the pr is created - however this will require an individual PAT in order to trigger the testing workflows properly

closes #15

### CODE REVIEW

**Comment by nekowinston** [comment]
Can't we use something like nvfetcher to automate updates? I've had a great time with it on my NUR, I think keeping the amount of inputs down is worthwhile. The inputs will only get worse when more are added regarding size and the amount of lines that show up in `nix flake metadata`.

I'd also like to add *everything* that's in the Nix flake from our git repositories, and not wait on nixpkgs to update. It would make sense to have our self-maintained derivations here, IMO.

**Comment by getchoo** [comment]
> Can't we use something like nvfetcher to automate updates?

honestly i thought flake inputs would be the simplest way to handle it, but after using it i barely noticed a difference lol. it's been added 👍🏻 

> I'd also like to add everything that's in the Nix flake from our git repositories, and not wait on nixpkgs to update. It would make sense to have our self-maintained derivations here, IMO.

i'll put this into a different pr, as this is already big enough and i have work in a bit :p

**Comment by nekowinston** [comment]
Glad that my suggestion of nvfetcher was of use 😄 

> i'll put this into a different pr, as this is already big enough and i have work in a bit :p

Absolutely, that was me just sharing my vision for what ctp/nix could be used for, not a comment on this PR 👍

**Comment by Scrumplex** [comment]
> honestly i thought flake inputs would be the simplest way to handle it

I would argue that flakes could have the advantage of allowing users to override inputs. On the other hand, this seems very niche, and perhaps we could support this another way in the future if anyone needs it.

**Comment by getchoo** [comment]
this will need to be rebased, so draft for now 🐈

**Pull request merged**
